-- PostgreSQL port of schema.sql.
--
-- Sep 2, 2026. Deliberately NOT idiomatic Postgres. The rule followed
-- throughout is: change the dialect, not the data shapes — because 420 tests
-- and 183 query sites assert against the shapes SQLite produced, and a port
-- that also "improves" them stops being reviewable.
--
-- The three that matter, and why:
--
--   REAL -> DOUBLE PRECISION, not NUMERIC.
--     NUMERIC is the correct type for money and this schema should eventually
--     use it. But node-postgres returns NUMERIC as a STRING (arbitrary
--     precision cannot fit a JS number), so `total_amount` would come back
--     "1500.00" instead of 1500, and every assertion and arithmetic operation
--     on it would silently change behaviour. Port first, fix money later, as
--     its own change with its own tests.
--
--   Booleans stay INTEGER.
--     is_active, is_read, is_test_account are 0/1 and the tests assert
--     `toBe(1)`. A real BOOLEAN would return true/false and break them all
--     for no functional gain during a port.
--
--   Timestamps stay TEXT holding ISO-8601.
--     The app writes `new Date().toISOString()` and the code SORTS AND
--     COMPARES these as strings (e.g. next_attempt_at <= ?, ORDER BY
--     created_at). A real timestamptz would be better, but mixing the two
--     during a port means string/timestamp comparisons that fail in
--     non-obvious ways. Note the default below reproduces JS's exact format,
--     including the T, the three fractional digits and the Z — a default of
--     now()::text would produce '2026-09-02 08:00:00.123456', which sorts
--     DIFFERENTLY as a string and would quietly corrupt every ordering.
--
-- AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY (not ALWAYS): tests and
-- fixtures sometimes insert explicit ids, which ALWAYS would reject.

-- Matches JavaScript's Date.toISOString() exactly: 2026-09-02T08:00:00.123Z
CREATE OR REPLACE FUNCTION iso_now() RETURNS TEXT
  LANGUAGE sql STABLE AS
$$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('medrep','finance','dispatch','management','admin')),
  is_active INTEGER DEFAULT 1,
  is_test_account INTEGER DEFAULT 0,
  -- ── Sep 9, 2026: admin approval for self-service sign-ups ──────────────────
  --
  -- Separate from `is_active` on purpose, because they answer different
  -- questions and conflating them loses one of the answers:
  --
  --   is_active       — has an admin switched this account off? (Deactivate)
  --   approval_status — has an admin ever vetted this sign-up at all?
  --
  -- A rejected applicant and a deactivated employee both cannot log in, but
  -- they are not the same thing, and an admin looking at the user list needs
  -- to tell "never approved" from "was approved, then disabled".
  --
  -- DEFAULT 'approved' is what makes this safe to add to a live database:
  -- every account that already exists was created before approval was a
  -- concept, so treating them as approved is the only reading that does not
  -- lock the entire company out on deploy. Only POST /api/auth/register
  -- writes 'pending', explicitly.
  approval_status TEXT NOT NULL DEFAULT 'approved'
    CHECK(approval_status IN ('pending','approved','rejected')),
  approved_at TEXT,
  -- Who decided. Nullable: NULL for accounts that predate this, and for ones
  -- an admin created directly (which are approved by the act of creating them).
  approved_by INTEGER REFERENCES users(id),

  first_name TEXT,
  middle_name TEXT,
  last_name TEXT,
  display_name TEXT,
  division TEXT,
  sub_division TEXT,
  -- SQLite had this VIRTUAL; Postgres only supports STORED. Same value, and
  -- still impossible to drift, which was the point: there is no stored string
  -- for a code path to forget to update, only a definition.
  salesperson TEXT GENERATED ALWAYS AS (
    CASE
      WHEN division IS NULL OR TRIM(division) = '' THEN NULL
      WHEN display_name IS NULL OR TRIM(display_name) = '' THEN NULL
      ELSE TRIM(division) || ' | ' || TRIM(display_name)
    END
  ) STORED,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('credit','direct')),
  credit_limit DOUBLE PRECISION DEFAULT 0 CHECK(credit_limit >= 0),
  contact_person TEXT,
  contact_number TEXT,
  address TEXT,
  is_active INTEGER DEFAULT 1,
  zoho_contact_id TEXT,
  source TEXT DEFAULT 'local' CHECK(source IN ('local','zoho')),
  last_synced_at TEXT,
  category TEXT CHECK(category IS NULL OR category IN ('doctor','hospital','distributor','pwd')),
  -- Sep 8, 2026: TIN (Tax Identification Number — a Philippines BIR
  -- requirement). Zoho refuses to create a Sales Order for a "business"
  -- sub-type contact with no cf_tin value, so this exists to fix that from
  -- this app rather than requiring a human to edit the contact in Zoho
  -- directly. Nullable, no default — most existing customers won't have
  -- one yet. Pushed to Zoho's cf_tin custom field by
  -- zoho.updateContactTin() (see customers.controller.js's
  -- updateCustomerTin) — a narrow, deliberate exception to this app's
  -- otherwise create-only Zoho write policy (see ZohoAdapter.js).
  tin TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL CHECK(unit_price >= 0),
  unit TEXT DEFAULT 'pc',
  stock INTEGER DEFAULT 0 CHECK(stock >= 0),
  zoho_item_id TEXT,
  zoho_stock DOUBLE PRECISION,
  zoho_price DOUBLE PRECISION,
  last_synced_at TEXT,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS order_id_sequences (
  prefix TEXT PRIMARY KEY,
  seq INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  getmeds_order_id TEXT UNIQUE NOT NULL,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  medrep_id INTEGER NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN (
    'draft', 'pending_management_approval', 'submitted', 'validating', 'so_pending', 'so_created',
    'ready_for_finance_verified', 'ready_for_draft_invoice',
    'ready_for_invoice_sent', 'ready_for_dispatch',
    'picking_packing', 'dispatched', 'tracking_shared',
    'completed', 'on_hold', 'exception', 'cancelled', 'deleted'
  )),
  customer_type TEXT NOT NULL CHECK(customer_type IN ('credit','direct')),
  total_amount DOUBLE PRECISION DEFAULT 0 CHECK(total_amount >= 0),
  delivery_address TEXT NOT NULL,
  delivery_notes TEXT,
  intake_courier TEXT,
  intake_doctor TEXT,
  intake_hospital TEXT,
  intake_patient TEXT,
  intake_mop TEXT,
  intake_receiver TEXT,
  intake_contact_no TEXT,
  intake_source TEXT,
  intake_pls_give TEXT,
  -- ── Sep 9, 2026: "Master Form" intake fields ───────────────────────────────
  --
  -- Five fields the order form collects that had nowhere to live. All
  -- nullable: POST /api/orders stays accepting an order without them, the way
  -- every intake_* field before them does, so the form's requirements remain a
  -- client-side UX guarantee rather than something that rejects other callers.

  -- Zoho's own "Expected Shipment Date" (salesorder.shipment_date). The one
  -- field of the five that maps to a REAL Zoho field rather than being local
  -- bookkeeping — see LiveZohoAdapter's createSalesOrder.
  intake_expected_shipment_date TEXT,

  -- Guarantee Letter number, for the PAP/DSWD hospital flow. Local only: this
  -- org has no Zoho custom field for it, and inventing a customfield_id is how
  -- the Division field broke on Sep 8.
  intake_gl_number TEXT,

  -- Who physically receives a hospital delivery. An enum rather than free
  -- text, for the reason the division field taught: 'patient', 'Patient',
  -- 'pt' and 'the patient' are four answers to the same question and nothing
  -- downstream can count them. The receiver's NAME stays intake_receiver.
  intake_receiver_type TEXT CHECK(intake_receiver_type IS NULL OR intake_receiver_type IN ('patient','representative')),

  -- Is the customer themselves the prescribing doctor? 1 yes, 0 no, NULL not
  -- answered (every order raised before this field existed). When 0, the
  -- doctor is named separately in intake_doctor.
  intake_is_doctor INTEGER CHECK(intake_is_doctor IS NULL OR intake_is_doctor IN (0,1)),

  -- The TIN as it stood on THIS order. customers.tin is the live value and can
  -- change; this is the snapshot, so an order raised before a correction still
  -- shows what was actually sent.
  intake_tin TEXT,
  sales_order_date TEXT,
  intake_delivery_method TEXT,
  intake_terms TEXT,
  intake_payment_terms TEXT,
  invoicing_from TEXT CHECK(invoicing_from IS NULL OR invoicing_from IN ('2mg Incorporated', 'Getmeds Philippines Inc.')),
  zoho_so_id TEXT,
  zoho_so_number TEXT,
  zoho_so_status TEXT,
  -- ── Sep 10, 2026: Zoho's four status axes, stored as Zoho reports them ─────
  --
  -- Zoho does not track one status. It tracks four independent ones, and the
  -- single `status` field everyone reaches for is only a rollup of them:
  --
  --   order_status     draft -> open -> closed
  --   invoiced_status  not_invoiced -> partially_invoiced -> invoiced
  --   paid_status      unpaid -> partially_paid -> paid
  --   shipped_status   not_shipped -> partially_shipped -> shipped -> fulfilled
  --
  -- Reading only the rollup is what left 58,289 orders that were finished in
  -- Zoho sitting at 'ready_for_finance_verified' in this app: `status:
  -- fulfilled` was mapped as though it were merely confirmed, and the fields
  -- that said invoiced/paid/shipped were never looked at.
  --
  -- Stored rather than re-derived because they answer questions our own single
  -- `status` column cannot — "invoiced but not yet shipped" is two axes, not
  -- one — and because they come free with the list walk, so keeping them costs
  -- nothing and re-fetching them costs an API call per order.
  zoho_order_status TEXT,
  zoho_invoiced_status TEXT,
  zoho_paid_status TEXT,
  zoho_shipped_status TEXT,
  zoho_invoice_id TEXT,
  zoho_invoice_number TEXT,
  zoho_sync_status TEXT DEFAULT 'pending' CHECK(zoho_sync_status IN ('pending','synced','failed','skipped')),
  last_reconciled_at TEXT,
  -- Sep 9, 2026: when this order's FULL Zoho detail was last pulled — its line
  -- items, and Zoho's own Comments & History log.
  --
  -- The import has two tiers, and this column is what tells them apart. Zoho's
  -- List Sales Orders response is cheap (one call per 200 orders) and carries
  -- enough to create the order row: number, customer, total, date, salesperson,
  -- status. Line items and history are not in it — those need a GET per order,
  -- two calls each, against an API with a per-minute rate limit and a daily
  -- budget. At this org's 65,000+ Sales Orders that is ~130,000 calls, so it
  -- cannot be one click.
  --
  -- So every Sales Order is adopted from the list (NULL here — "we know this
  -- order exists and what it is worth"), and the expensive detail is filled in
  -- afterwards, a batch per import run and on demand whenever someone opens
  -- the order. NULL is therefore normal and not an error state; it means
  -- "summary only, so far".
  zoho_detail_synced_at TEXT,
  exception_reason TEXT,
  -- Sep 4, 2026: why this order has NO proof of payment attached.
  --
  -- Required by the order form when no file is staged — see OrderForm.jsx. It
  -- is a gate on the FORM, not on Finance: the API still accepts an order with
  -- neither, because the proof itself uploads AFTER create (it needs the order
  -- id for its storage path) and a server-side requirement would reject every
  -- order that is about to get one.
  --
  -- An enum rather than free text, for the reason the division field taught on
  -- Sep 2: 'terms', 'on terms', 'Terms' and 'w/ terms' are four answers to the
  -- same question, and nothing downstream can count them.
  no_payment_proof_reason TEXT CHECK(no_payment_proof_reason IS NULL OR no_payment_proof_reason IN (
    'on_payment_terms', 'payment_to_follow', 'paid_no_slip', 'other'
  )),
  no_payment_proof_note TEXT,
  -- Sep 5, 2026 (3): THIS order's Sub-division — editable at order creation
  -- by whoever raises it (medrep or management), unlike Division (which
  -- always comes from the ordering MedRep's account, since it also drives
  -- their Salesperson). Defaults to the account's own users.sub_division
  -- when not explicitly sent — see orders.controller.js's create(). No
  -- CHECK here: validated in the controller against
  -- SUB_DIVISIONS_BY_DIVISION only for the four Divisions that have a fixed
  -- list, same reasoning as users.division/users.sub_division never having
  -- a DB-level constraint.
  sub_division TEXT,
  -- Sep 5, 2026 (4): THIS order's Division and Salesperson — like
  -- sub_division above, editable at order creation, but ONLY by Management
  -- (a MedRep's Division/Salesperson always come straight from their own
  -- account; orders.controller.js's create() ignores these two fields from
  -- anyone else). NULL is the normal case even for a Management order —
  -- it means "use whatever the ordering MedRep's account has" (or nothing,
  -- if none was picked); a non-NULL value here always wins over the
  -- account join at submit() time. division is checked against the same
  -- 15-entry DIVISIONS list Sign Up/Profile Settings use; salesperson is
  -- checked live against Zoho's own Salesperson list (never a fixed local
  -- one — see salespersonService.js), since Zoho itself is what rejects an
  -- unrecognized name.
  division TEXT,
  salesperson TEXT,
  -- Sep 8, 2026 (3): the identity of the admin/management account that
  -- created this order (the order form's "Admin" field — previously shown
  -- but never sent to Zoho). Set once at create() time, NULL when a MedRep
  -- created their own order (nothing separate to report — see
  -- orders.controller.js's gmLeadId note). Sent to Zoho's "GM Lead ID"
  -- custom field (cf_gm_lead_id, confirmed live on this org).
  gm_lead_id TEXT,
  created_at TEXT DEFAULT iso_now(),
  submitted_at TEXT,
  updated_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL CHECK(quantity > 0),
  unit_price DOUBLE PRECISION NOT NULL CHECK(unit_price >= 0),
  subtotal DOUBLE PRECISION NOT NULL CHECK(subtotal >= 0),
  discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(discount_amount >= 0),
  tax_percent DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(tax_percent >= 0),
  tax_label TEXT,
  line_total DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(line_total >= 0)
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','rejected')),
  payment_reference TEXT,
  payment_date TEXT,
  amount DOUBLE PRECISION CHECK(amount IS NULL OR amount >= 0),
  payment_method TEXT,
  notes TEXT,
  verified_by INTEGER REFERENCES users(id),
  verified_at TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS dispatch_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','picking','packing','dispatched')),
  courier TEXT,
  tracking_number TEXT,
  dispatch_notes TEXT,
  dispatched_by INTEGER REFERENCES users(id),
  dispatched_at TEXT,
  created_at TEXT DEFAULT iso_now()
);

-- Proof of payment (Sep 4, 2026).
--
-- The deposit slip, transfer screenshot or receipt a MedRep attaches to an
-- order. It is the EVIDENCE Finance looks at when deciding the account check
-- at `ready_for_finance_verified` — the stage that already gates invoicing.
-- It is not a second decision beside that one.
--
-- Shaped deliberately like `payments` above: its own row, its own
-- pending/verified/rejected status, joined onto the order. It is NOT a
-- pipeline stage — `orders.status`, workflow/stateMachine.js and
-- services/orderCompletionService.js are all untouched by it. Making it a
-- status would have meant a CHECK migration and edits to every queue query,
-- which is the class of change 2026-09-01-status-rename.md documents going
-- wrong.
--
-- It is also NOT the same thing as `payments`. That table is Zoho's record of
-- a Customer Payment, arriving by webhook, and it is what
-- orderCompletionService.js means by "paid". This table is the customer's
-- CLAIM to have paid. A verified proof does not make an order paid.
--
-- `storage_path` is a key into the private Supabase Storage bucket, never a
-- URL: view URLs are signed on read with a short TTL and are not stored
-- anywhere. The file itself never passes through the API — the browser PUTs
-- it straight to Supabase against a signed upload URL, because Vercel caps
-- request bodies at 4.5 MB and a phone photo routinely exceeds that.
--
-- order_id is UNIQUE: one proof per order, matching payments and
-- dispatch_records. Re-uploading after a rejection upserts this row and
-- clears the verification columns rather than inserting a second one.
-- Sep 5, 2026: generalized from a single "one proof per order" row into a
-- typed, multi-row attachment table — matches Zoho's own "Attach File(s) to
-- Sales Order" on the Sales Order screen, but with each file tagged so this
-- app still knows which ones are evidence for Finance's account check.
-- `order_id` is no longer UNIQUE: an order can carry any number of
-- attachments. `file_type` distinguishes the two kinds:
--   'payment_proof' — a deposit slip, transfer screenshot or receipt. This is
--                     the evidence Finance's account check
--                     (ready_for_finance_verified) acts on — verified/
--                     rejected exactly as before, just no longer capped at one
--                     per order (a rejected slip plus its replacement can both
--                     exist, for instance).
--   'purchase_order' — a PO document from the customer. Purely informational,
--                     same as 'other' below (added Sep 5, 2026).
--   'other'         — anything else worth attaching to the order (an
--                     authorization letter, a signed contract). Purely
--                     informational: nothing in this app verifies, rejects,
--                     or otherwise acts on an 'other'/'purchase_order'
--                     attachment. `status` stays 'pending' for these rows
--                     and is simply not shown.
CREATE TABLE IF NOT EXISTS payment_proofs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  -- Sep 9, 2026: 'gl', 'prescription' and 'id' added for the hospital
  -- (PAP/DSWD) flow, which requires all four of Guarantee Letter,
  -- Prescription, Proof of Payment and a photo ID before an order can be
  -- raised. Adding a value here means adding it to REQUIRED_FILE_TYPES in
  -- migrate.pg.js and FILE_TYPES in paymentProof.controller.js too — the
  -- three are checked against each other by the migration.
  file_type TEXT NOT NULL DEFAULT 'payment_proof' CHECK(file_type IN ('payment_proof','other','purchase_order','gl','prescription','id')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','rejected')),
  storage_path TEXT NOT NULL,
  file_name TEXT,
  content_type TEXT,
  file_size INTEGER CHECK(file_size IS NULL OR file_size >= 0),
  uploaded_by INTEGER REFERENCES users(id),
  uploaded_at TEXT DEFAULT iso_now(),
  verified_by INTEGER REFERENCES users(id),
  verified_at TEXT,
  rejection_reason TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS order_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  old_status TEXT,
  new_status TEXT,
  actor_id INTEGER REFERENCES users(id),
  actor_name TEXT,
  notes TEXT,
  metadata TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  recipient_id INTEGER REFERENCES users(id),
  channel TEXT NOT NULL CHECK(channel IN ('in_app','email_log','google_chat_log')),
  message TEXT NOT NULL,
  payload TEXT,
  is_read INTEGER DEFAULT 0,
  sent_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS zoho_sync_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  payload TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','succeeded','failed_permanent')),
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  next_attempt_at TEXT NOT NULL DEFAULT iso_now(),
  created_at TEXT DEFAULT iso_now(),
  updated_at TEXT DEFAULT iso_now()
);

-- ── Sep 10, 2026: who owns the Sales Orders imported from Zoho ──────────────
--
-- 60,817 orders came in from Zoho carrying a free-text `salesperson` string
-- and no idea which system account it belongs to. This table is the record of
-- that decision, made by a human, once per distinct Zoho string.
--
-- Why a table and not a one-off reassignment script:
--
--   * Later imports self-attribute. A decision made today applies to Sales
--     Orders pulled next month with no re-review.
--   * It is reversible. Change a row, re-apply, done.
--   * It is auditable. "Why does this rep own this order" has an answer with a
--     name and a date on it.
--
-- Why the decision is not computed: the strings are dirty in ways that make
-- automatic matching actively dangerous. Real examples from the live org —
-- 'MSA I WENDY MAE' uses a capital I rather than a pipe; 'MSA GILBERT DELA
-- CRUZ' has no separator at all; 'MSA | Dona Mae Lebumfacil' and
-- 'B2B |  DONA MAE LEBUMFACIL' are one person under two divisions. Normalise
-- hard enough to catch those and 'HOS | MANILA VACANT' starts looking like
-- 'HOS | Aaron Manila', which would hand one rep another's history. The system
-- suggests; a person decides.
-- ---------------------------------------------------------------------------
-- Sep 11, 2026: which orders a MANAGEMENT user may see and act on.
--
-- Until now every management user saw every order. The business runs three
-- managers with different remits: one owning the whole approval queue, and two
-- who each cover their own divisions.
--
-- A row here GRANTS visibility. There is no deny rule, and no row means no
-- access -- see services/orderScopeService.js for why this fails closed rather
-- than treating "nothing configured" as "no restrictions".
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Sep 11, 2026: admin accounts cannot be deleted, deactivated, or demoted.
--
-- Enforced in the DATABASE rather than only in the API because the API is not
-- the only way in. Every repair and provisioning script in scripts/ connects
-- with the same credentials and can issue any UPDATE or DELETE it likes -- one
-- of them removed two user rows earlier today. A rule that only lives in a
-- controller protects the one path somebody remembered to guard.
--
-- Three things are blocked, and the third is the one that gets missed: an
-- admin demoted to another role is not "deactivated" anywhere in the audit
-- trail, but the access is just as gone.
--
-- ESCAPE HATCH: a session that genuinely needs to (offboarding a departing
-- admin) can set the flag below first. It has to be typed on purpose, which is
-- the point -- accidents and stray scripts do not set session variables.
--
--   BEGIN;
--     SET LOCAL app.allow_admin_change = 'on';
--     UPDATE users SET is_active = 0 WHERE id = 1;
--   COMMIT;
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION protect_admin_accounts() RETURNS trigger AS $protect$
BEGIN
  -- Deliberate, per-transaction override. `true` as the second argument makes
  -- current_setting return NULL instead of erroring when the flag was never
  -- set, which is the normal case.
  IF current_setting('app.allow_admin_change', true) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  -- A TEST admin is not the system's administrator. Test Mode creates and
  -- tears down its own accounts (is_test_account = 1, see
  -- controllers/test.controller.js), and blocking that would make the teardown
  -- fail rather than make anything safer -- a real production admin always has
  -- is_test_account = 0.
  IF COALESCE(OLD.is_test_account, 0) = 1 THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.role = 'admin' THEN
      RAISE EXCEPTION 'Admin accounts cannot be deleted. Set app.allow_admin_change to override.'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN OLD;
  END IF;

  IF OLD.role = 'admin' THEN
    IF NEW.is_active = 0 THEN
      RAISE EXCEPTION 'Admin accounts cannot be deactivated. Set app.allow_admin_change to override.'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    IF NEW.role <> 'admin' THEN
      RAISE EXCEPTION 'An admin account cannot be changed to another role. Set app.allow_admin_change to override.'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
  END IF;

  RETURN NEW;
END;
$protect$ LANGUAGE plpgsql;

-- Dropped and recreated rather than CREATE IF NOT EXISTS: this file is applied
-- in full on every migration, and a trigger definition that changed would
-- otherwise be ignored on databases that already have the old one.
DROP TRIGGER IF EXISTS trg_protect_admin_update ON users;
CREATE TRIGGER trg_protect_admin_update
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION protect_admin_accounts();

DROP TRIGGER IF EXISTS trg_protect_admin_delete ON users;
CREATE TRIGGER trg_protect_admin_delete
  BEFORE DELETE ON users
  FOR EACH ROW EXECUTE FUNCTION protect_admin_accounts();

CREATE TABLE IF NOT EXISTS manager_order_scope (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- One of auth.controller's DIVISIONS, matched against orders.division.
  division TEXT NOT NULL,
  -- NULL means the WHOLE division; a value narrows to that sub-division only.
  --
  -- Deliberately free text rather than an enum. B2B has no fixed sub-division
  -- list, and B2B -> NBD/CRR is precisely the case this column exists for --
  -- though as of today neither appears on any order, because B2B's Zoho
  -- Salesperson field holds a person's name where HOS holds a territory.
  sub_division TEXT,
  created_at TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id)
);

-- The lookup is always "every rule for this user", on every scoped request.
CREATE INDEX IF NOT EXISTS idx_manager_order_scope_user ON manager_order_scope(user_id);

-- One rule per (user, division, sub-division). COALESCE because NULL is not
-- equal to NULL in a unique index, so without it a user could hold the same
-- whole-division grant many times over.
CREATE UNIQUE INDEX IF NOT EXISTS idx_manager_order_scope_unique
  ON manager_order_scope(user_id, division, COALESCE(sub_division, ''));

-- Scoped queries filter on division, and increasingly on both.
CREATE INDEX IF NOT EXISTS idx_orders_division ON orders(division);
CREATE INDEX IF NOT EXISTS idx_orders_division_sub ON orders(division, sub_division);

CREATE TABLE IF NOT EXISTS salesperson_mappings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The Zoho string EXACTLY as it appears on the Sales Order, trailing spaces
  -- and all. Matching is done on a normalised form (see
  -- services/salespersonMappingService.js), but what is stored is verbatim, so
  -- this table can always be traced back to what Zoho actually holds.
  zoho_salesperson TEXT NOT NULL UNIQUE,
  -- The system account that owns orders carrying this string. NULL for
  -- anything that is not a person, and for people who have not signed up yet
  -- or have left — see `kind`.
  user_id INTEGER REFERENCES users(id),
  -- What this string turned out to BE. Roughly half of the 171 distinct
  -- values are not people at all: 51 are territories ('HOS | LAGUNA',
  -- 'B&B | EAST AVE'), 13 are sales channels ('WEB', 'Shopee', 'Lazada').
  -- Recording that is the difference between "nobody has looked at this yet"
  -- and "somebody looked, and there is no person to assign".
  --   undecided — not yet reviewed (the default for a newly discovered string)
  --   person    — a real rep; user_id names them, or is NULL if they have no
  --               account yet or have left the company
  --   territory — a branch/area, stays Management-owned
  --   channel   — WEB/Shopee/Lazada/etc, stays Management-owned
  --   vacant    — explicitly nobody ('HOS | MANILA VACANT')
  kind TEXT NOT NULL DEFAULT 'undecided'
    CHECK(kind IN ('undecided','person','territory','channel','vacant')),
  notes TEXT,
  mapped_by INTEGER REFERENCES users(id),
  mapped_at TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE INDEX IF NOT EXISTS idx_salesperson_mappings_user ON salesperson_mappings(user_id);
CREATE INDEX IF NOT EXISTS idx_salesperson_mappings_kind ON salesperson_mappings(kind);

CREATE TABLE IF NOT EXISTS sync_state (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TEXT DEFAULT iso_now()
);

CREATE INDEX IF NOT EXISTS idx_orders_medrep_created ON orders(medrep_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_submitted ON orders(status, submitted_at ASC);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_events_order_created ON order_events(order_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread ON notifications(recipient_id, channel, is_read, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_active_name ON products(is_active, name);
CREATE INDEX IF NOT EXISTS idx_customers_active_name ON customers(is_active, name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_zoho_contact_id ON customers(zoho_contact_id) WHERE zoho_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_zoho_sync_queue_pending ON zoho_sync_queue(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_zoho_sync_queue_order ON zoho_sync_queue(order_id);

-- Finance's queue joins this on and sorts pending proofs oldest-first.
-- order_id already has a unique index from the UNIQUE constraint, so the
-- per-order lookup on the order page needs nothing extra.
CREATE INDEX IF NOT EXISTS idx_payment_proofs_status ON payment_proofs(status, uploaded_at ASC);
-- Sep 5, 2026: order_id lost its UNIQUE constraint above (multiple
-- attachments per order), so it needs its own index for the lookups every
-- attachment endpoint does (WHERE order_id = ?).
CREATE INDEX IF NOT EXISTS idx_payment_proofs_order_id ON payment_proofs(order_id);

-- The customer autocomplete searches ~95k rows with LIKE. SQLite's LIKE is
-- case-insensitive for ASCII by default; Postgres's is NOT. Those queries must
-- become ILIKE during the port or search quietly stops matching — this index
-- supports the case-insensitive form so it does not become a full scan.
CREATE INDEX IF NOT EXISTS idx_customers_name_lower ON customers(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_products_name_lower ON products(LOWER(name));
