-- PostgreSQL port of schema.sql.
--
-- Sep 2, 2026. Deliberately NOT idiomatic Postgres. The rule followed
-- throughout is: change the dialect, not the data shapes — because 420 tests
-- and 183 query sites assert against the shapes SQLite produced, and a port
-- that also "improves" them stops being reviewable.
--
-- The three that matter, and why:
--
--   REAL -> DOUBLE PRECISION, not NUMERIC.
--     NUMERIC is the correct type for money and this schema should eventually
--     use it. But node-postgres returns NUMERIC as a STRING (arbitrary
--     precision cannot fit a JS number), so `total_amount` would come back
--     "1500.00" instead of 1500, and every assertion and arithmetic operation
--     on it would silently change behaviour. Port first, fix money later, as
--     its own change with its own tests.
--
--   Booleans stay INTEGER.
--     is_active, is_read, is_test_account are 0/1 and the tests assert
--     `toBe(1)`. A real BOOLEAN would return true/false and break them all
--     for no functional gain during a port.
--
--   Timestamps stay TEXT holding ISO-8601.
--     The app writes `new Date().toISOString()` and the code SORTS AND
--     COMPARES these as strings (e.g. next_attempt_at <= ?, ORDER BY
--     created_at). A real timestamptz would be better, but mixing the two
--     during a port means string/timestamp comparisons that fail in
--     non-obvious ways. Note the default below reproduces JS's exact format,
--     including the T, the three fractional digits and the Z — a default of
--     now()::text would produce '2026-09-02 08:00:00.123456', which sorts
--     DIFFERENTLY as a string and would quietly corrupt every ordering.
--
-- AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY (not ALWAYS): tests and
-- fixtures sometimes insert explicit ids, which ALWAYS would reject.

-- Matches JavaScript's Date.toISOString() exactly: 2026-09-02T08:00:00.123Z
CREATE OR REPLACE FUNCTION iso_now() RETURNS TEXT
  LANGUAGE sql STABLE AS
$$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('medrep','finance','dispatch','management','admin')),
  is_active INTEGER DEFAULT 1,
  is_test_account INTEGER DEFAULT 0,
  first_name TEXT,
  middle_name TEXT,
  last_name TEXT,
  display_name TEXT,
  division TEXT,
  sub_division TEXT,
  -- SQLite had this VIRTUAL; Postgres only supports STORED. Same value, and
  -- still impossible to drift, which was the point: there is no stored string
  -- for a code path to forget to update, only a definition.
  salesperson TEXT GENERATED ALWAYS AS (
    CASE
      WHEN division IS NULL OR TRIM(division) = '' THEN NULL
      WHEN display_name IS NULL OR TRIM(display_name) = '' THEN NULL
      ELSE TRIM(division) || ' | ' || TRIM(display_name)
    END
  ) STORED,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('credit','direct')),
  credit_limit DOUBLE PRECISION DEFAULT 0 CHECK(credit_limit >= 0),
  contact_person TEXT,
  contact_number TEXT,
  address TEXT,
  is_active INTEGER DEFAULT 1,
  zoho_contact_id TEXT,
  source TEXT DEFAULT 'local' CHECK(source IN ('local','zoho')),
  last_synced_at TEXT,
  category TEXT CHECK(category IS NULL OR category IN ('doctor','hospital','distributor','pwd')),
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL CHECK(unit_price >= 0),
  unit TEXT DEFAULT 'pc',
  stock INTEGER DEFAULT 0 CHECK(stock >= 0),
  zoho_item_id TEXT,
  zoho_stock DOUBLE PRECISION,
  zoho_price DOUBLE PRECISION,
  last_synced_at TEXT,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS order_id_sequences (
  prefix TEXT PRIMARY KEY,
  seq INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  getmeds_order_id TEXT UNIQUE NOT NULL,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  medrep_id INTEGER NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN (
    'draft', 'submitted', 'validating', 'so_pending', 'so_created',
    'ready_for_finance_verified', 'ready_for_draft_invoice',
    'ready_for_invoice_sent', 'ready_for_dispatch',
    'picking_packing', 'dispatched', 'tracking_shared',
    'completed', 'on_hold', 'exception', 'cancelled', 'deleted'
  )),
  customer_type TEXT NOT NULL CHECK(customer_type IN ('credit','direct')),
  total_amount DOUBLE PRECISION DEFAULT 0 CHECK(total_amount >= 0),
  delivery_address TEXT NOT NULL,
  delivery_notes TEXT,
  intake_courier TEXT,
  intake_doctor TEXT,
  intake_hospital TEXT,
  intake_patient TEXT,
  intake_mop TEXT,
  intake_receiver TEXT,
  intake_contact_no TEXT,
  intake_source TEXT,
  intake_pls_give TEXT,
  sales_order_date TEXT,
  intake_delivery_method TEXT,
  intake_terms TEXT,
  intake_payment_terms TEXT,
  invoicing_from TEXT CHECK(invoicing_from IS NULL OR invoicing_from IN ('2mg Incorporated', 'Getmeds Philippines Inc.')),
  zoho_so_id TEXT,
  zoho_so_number TEXT,
  zoho_so_status TEXT,
  zoho_invoice_id TEXT,
  zoho_invoice_number TEXT,
  zoho_sync_status TEXT DEFAULT 'pending' CHECK(zoho_sync_status IN ('pending','synced','failed','skipped')),
  last_reconciled_at TEXT,
  exception_reason TEXT,
  created_at TEXT DEFAULT iso_now(),
  submitted_at TEXT,
  updated_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL CHECK(quantity > 0),
  unit_price DOUBLE PRECISION NOT NULL CHECK(unit_price >= 0),
  subtotal DOUBLE PRECISION NOT NULL CHECK(subtotal >= 0),
  discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(discount_amount >= 0),
  tax_percent DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(tax_percent >= 0),
  tax_label TEXT,
  line_total DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK(line_total >= 0)
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','rejected')),
  payment_reference TEXT,
  payment_date TEXT,
  amount DOUBLE PRECISION CHECK(amount IS NULL OR amount >= 0),
  payment_method TEXT,
  notes TEXT,
  verified_by INTEGER REFERENCES users(id),
  verified_at TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS dispatch_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','picking','packing','dispatched')),
  courier TEXT,
  tracking_number TEXT,
  dispatch_notes TEXT,
  dispatched_by INTEGER REFERENCES users(id),
  dispatched_at TEXT,
  created_at TEXT DEFAULT iso_now()
);

-- Proof of payment (Sep 4, 2026).
--
-- The deposit slip, transfer screenshot or receipt a MedRep attaches to an
-- order. It is the EVIDENCE Finance looks at when deciding the account check
-- at `ready_for_finance_verified` — the stage that already gates invoicing.
-- It is not a second decision beside that one.
--
-- Shaped deliberately like `payments` above: its own row, its own
-- pending/verified/rejected status, joined onto the order. It is NOT a
-- pipeline stage — `orders.status`, workflow/stateMachine.js and
-- services/orderCompletionService.js are all untouched by it. Making it a
-- status would have meant a CHECK migration and edits to every queue query,
-- which is the class of change 2026-09-01-status-rename.md documents going
-- wrong.
--
-- It is also NOT the same thing as `payments`. That table is Zoho's record of
-- a Customer Payment, arriving by webhook, and it is what
-- orderCompletionService.js means by "paid". This table is the customer's
-- CLAIM to have paid. A verified proof does not make an order paid.
--
-- `storage_path` is a key into the private Supabase Storage bucket, never a
-- URL: view URLs are signed on read with a short TTL and are not stored
-- anywhere. The file itself never passes through the API — the browser PUTs
-- it straight to Supabase against a signed upload URL, because Vercel caps
-- request bodies at 4.5 MB and a phone photo routinely exceeds that.
--
-- order_id is UNIQUE: one proof per order, matching payments and
-- dispatch_records. Re-uploading after a rejection upserts this row and
-- clears the verification columns rather than inserting a second one.
CREATE TABLE IF NOT EXISTS payment_proofs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','rejected')),
  storage_path TEXT NOT NULL,
  file_name TEXT,
  content_type TEXT,
  file_size INTEGER CHECK(file_size IS NULL OR file_size >= 0),
  uploaded_by INTEGER REFERENCES users(id),
  uploaded_at TEXT DEFAULT iso_now(),
  verified_by INTEGER REFERENCES users(id),
  verified_at TEXT,
  rejection_reason TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS order_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  old_status TEXT,
  new_status TEXT,
  actor_id INTEGER REFERENCES users(id),
  actor_name TEXT,
  notes TEXT,
  metadata TEXT,
  created_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  recipient_id INTEGER REFERENCES users(id),
  channel TEXT NOT NULL CHECK(channel IN ('in_app','email_log','google_chat_log')),
  message TEXT NOT NULL,
  payload TEXT,
  is_read INTEGER DEFAULT 0,
  sent_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS zoho_sync_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  payload TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','succeeded','failed_permanent')),
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  next_attempt_at TEXT NOT NULL DEFAULT iso_now(),
  created_at TEXT DEFAULT iso_now(),
  updated_at TEXT DEFAULT iso_now()
);

CREATE TABLE IF NOT EXISTS sync_state (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TEXT DEFAULT iso_now()
);

CREATE INDEX IF NOT EXISTS idx_orders_medrep_created ON orders(medrep_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_submitted ON orders(status, submitted_at ASC);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_events_order_created ON order_events(order_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread ON notifications(recipient_id, channel, is_read, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_active_name ON products(is_active, name);
CREATE INDEX IF NOT EXISTS idx_customers_active_name ON customers(is_active, name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_zoho_contact_id ON customers(zoho_contact_id) WHERE zoho_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_zoho_sync_queue_pending ON zoho_sync_queue(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_zoho_sync_queue_order ON zoho_sync_queue(order_id);

-- Finance's queue joins this on and sorts pending proofs oldest-first.
-- order_id already has a unique index from the UNIQUE constraint, so the
-- per-order lookup on the order page needs nothing extra.
CREATE INDEX IF NOT EXISTS idx_payment_proofs_status ON payment_proofs(status, uploaded_at ASC);

-- The customer autocomplete searches ~95k rows with LIKE. SQLite's LIKE is
-- case-insensitive for ASCII by default; Postgres's is NOT. Those queries must
-- become ILIKE during the port or search quietly stops matching — this index
-- supports the case-insensitive form so it does not become a full scan.
CREATE INDEX IF NOT EXISTS idx_customers_name_lower ON customers(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_products_name_lower ON products(LOWER(name));
